[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2024"
authors = ["{{author-name}} <{{author-email}}>"]
description = "{{description}}"
license = "MIT"
repository = "https://github.com/{{github-username}}/{{project-name}}"
documentation = "https://docs.rs/{{project-name}}"
homepage = "https://github.com/{{github-username}}/{{project-name}}"
categories = ["development-tools"] # Update with appropriate categories
keywords = ["rust"] # Update with relevant keywords (max 5)
readme = "README.md"
rust-version = "1.85"

[dependencies]

[dev-dependencies]

[features]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
rust.missing_docs = "warn"
rust.missing_debug_implementations = "warn"
clippy.all = "warn"
clippy.style = "warn"
clippy.correctness = "warn"
clippy.complexity = "warn"
clippy.suspicious = "warn"
clippy.perf = "warn"
clippy.pedantic = "warn"
clippy.nursery = "warn"
clippy.cargo = "warn"